# Generated by Django 3.0.3 on 2026-07-30 13:56

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('date', models.CharField(max_length=20)),
                ('actual', models.FloatField(blank=True, null=True)),
                ('forecast', models.FloatField(blank=True, null=True)),
                ('previous', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('note', models.TextField(blank=True)),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '關注事件',
                'verbose_name_plural': '關注事件',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('headline', '頭條'), ('tsmc', '台積電'), ('fed', '聯準會')], db_index=True, max_length=16)),
                ('rank', models.IntegerField(default=0)),
                ('title', models.TextField()),
                ('summary', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('url', models.URLField(blank=True, max_length=1000)),
                ('time', models.CharField(blank=True, max_length=40)),
                ('tags', jsonfield.fields.JSONField(blank=True, default=list)),
                ('stance', models.CharField(blank=True, max_length=16, null=True)),
            ],
            options={
                'verbose_name': '新聞條目',
                'verbose_name_plural': '新聞條目',
                'ordering': ['category', 'rank'],
            },
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(db_index=True, max_length=32, unique=True)),
                ('payload', jsonfield.fields.JSONField(blank=True, default=dict)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '快照 (Snapshot)',
                'verbose_name_plural': '快照 (Snapshot)',
            },
        ),
        migrations.CreateModel(
            name='Valuation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=12, unique=True)),
                ('updated_at', models.CharField(blank=True, max_length=40)),
                ('payload', jsonfield.fields.JSONField(default=dict)),
            ],
            options={
                'verbose_name': '估值河流圖',
                'verbose_name_plural': '估值河流圖',
            },
        ),
        migrations.CreateModel(
            name='WatchlistItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12, unique=True)),
                ('symbol', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=40)),
                ('position', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '觀察名單',
                'verbose_name_plural': '觀察名單',
                'ordering': ['position'],
            },
        ),
    ]
