# Generated by Django 5.2.5 on 2026-09-27 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceCache',
            fields=[
                ('symbol', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField()),
                ('first_date', models.DateField(null=True)),
                ('last_date', models.DateField(null=True)),
                ('rows', models.IntegerField(default=0)),
                ('payload', models.TextField()),
            ],
            options={
                'verbose_name': '回測行情快取',
            },
        ),
    ]
