# Generated by Django 2.2.5 on 2020-06-19 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiserver', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strategy_robot',
            old_name='yea_return',
            new_name='year_return',
        ),
    ]
