# Generated by Django 2.2.5 on 2020-07-14 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiserver', '0002_auto_20200619_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy_robot',
            name='type',
            field=models.TextField(default=''),
        ),
    ]
