# Generated by Django 2.2.5 on 2020-07-14 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiserver', '0003_strategy_robot_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategy_robot',
            name='type',
        ),
        migrations.AddField(
            model_name='now_chose',
            name='type',
            field=models.TextField(default=''),
        ),
    ]
