# Generated by Django 2.2.5 on 2020-07-14 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiserver', '0005_history_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='botTechnicCurrent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_update', models.TextField(default='')),
                ('stock_name', models.TextField(default='')),
                ('start_date', models.TextField(default='')),
                ('start_price', models.TextField(default='')),
                ('over_date', models.TextField(default='')),
                ('current_price', models.TextField(default='')),
                ('now_return', models.TextField(default='')),
                ('type', models.TextField(default='')),
            ],
            options={
                'db_table': 'botTechnicCurrent',
            },
        ),
        migrations.CreateModel(
            name='technicHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.TextField(default='')),
                ('start_date', models.TextField(default='')),
                ('buy_price', models.TextField(default='')),
                ('over_date', models.TextField(default='')),
                ('sell_price', models.TextField(default='')),
                ('return_value', models.TextField(default='')),
                ('type', models.TextField(default='')),
            ],
            options={
                'db_table': 'technicHistory',
            },
        ),
        migrations.RenameModel(
            old_name='now_chose',
            new_name='basicCurrent',
        ),
        migrations.RenameModel(
            old_name='history',
            new_name='basicHistory',
        ),
        migrations.RenameModel(
            old_name='strategy_robot',
            new_name='bot',
        ),
        migrations.AlterModelTable(
            name='basiccurrent',
            table='basicCurrent',
        ),
        migrations.AlterModelTable(
            name='basichistory',
            table='basicHistory',
        ),
    ]
