# Generated by Django 2.2.5 on 2020-07-14 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiserver', '0006_auto_20200714_1018'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bot',
            table='bot',
        ),
    ]
