# Generated by Django 2.2.5 on 2020-07-14 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiserver', '0007_auto_20200714_1019'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='botTechnicCurrent',
            new_name='TechnicCurrent',
        ),
        migrations.AlterModelTable(
            name='techniccurrent',
            table='technicCurrent',
        ),
    ]
