# Generated by Django 2.2.5 on 2020-07-14 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiserver', '0008_auto_20200714_1020'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='techniccurrent',
            table='technicCurrent',
        ),
    ]
