# Generated by Django 2.2.5 on 2020-09-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiserver', '0009_auto_20200714_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='article_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
                ('title_picture', models.TextField(default='')),
                ('abstract', models.TextField(default='')),
                ('author_picture', models.TextField(default='')),
                ('author_name', models.TextField(default='')),
                ('date', models.TextField(default='')),
                ('link', models.TextField(default='')),
            ],
            options={
                'db_table': 'article_1',
            },
        ),
    ]
