# Generated by Django 2.2.4 on 2020-10-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiserver', '0010_article_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='article_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
                ('title_picture', models.TextField(default='')),
                ('abstract', models.TextField(default='')),
                ('author_picture', models.TextField(default='')),
                ('author_name', models.TextField(default='')),
                ('date', models.TextField(default='')),
                ('link', models.TextField(default='')),
            ],
            options={
                'db_table': 'article_2',
            },
        ),
    ]
