# Generated by Django 3.2.3 on 2025-06-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiserver', '0011_article_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='月份標籤，例如：2025年一月份績效', max_length=100)),
                ('date_range', models.CharField(help_text='例如：2025-01-11~2025-02-10', max_length=50)),
                ('etf0050_return', models.FloatField(help_text='ETF 0050 的績效（百分比）')),
                ('strategy_return', models.FloatField(help_text='我的策略績效（百分比）')),
            ],
            options={
                'db_table': 'MonthlyPerformance',
            },
        ),
    ]
