# Generated by Django 6.0.2 on 2026-09-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiserver', '0013_auto_20250623_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_1',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='article_1',
            name='slug',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='article_1',
            name='source_docx',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='article_1',
            name='updated',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='article_2',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='article_2',
            name='slug',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='article_2',
            name='source_docx',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='article_2',
            name='updated',
            field=models.TextField(blank=True, default=''),
        ),
    ]
