# Generated by Django 5.2.16 on 2026-07-27 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PushLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(max_length=8)),
                ('push_mode', models.CharField(max_length=16)),
                ('message', models.TextField()),
                ('signal_count', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=16)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WatchTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=32, unique=True)),
                ('display_name', models.CharField(max_length=32)),
                ('asset_class', models.CharField(max_length=16)),
                ('market', models.CharField(db_index=True, max_length=8)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SignalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator', models.CharField(max_length=16)),
                ('direction', models.CharField(max_length=8)),
                ('trigger_date', models.DateField()),
                ('triggered_at', models.DateTimeField()),
                ('detail', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='notify.watchtarget')),
            ],
            options={
                'indexes': [models.Index(fields=['target', 'indicator', 'direction', 'triggered_at'], name='idx_signal_dedup')],
            },
        ),
    ]
