# Generated by Django 5.2.5 on 2026-08-07 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0002_seed_targets'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushlog',
            name='channel',
            field=models.CharField(default='line', max_length=16),
        ),
    ]
